# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Farmgazer-2-new

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30  # 添加超时设置

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 清理和重新安装
      - name: Clean install and build
        run: |
          rm -rf node_modules
          rm -rf .next
          npm ci
          npm run build
        env:
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
          AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          NODE_ENV: production

      # 优化部署包大小
      - name: Optimize deployment package
        run: |
          echo "优化部署包大小..."
          rm -rf node_modules/.cache
          find . -name "*.map" -type f -delete
          npm prune --production
          du -sh . node_modules .next

      # 在构建后立即验证 .next 目录
      - name: Verify build output
        run: |
          echo "Listing .next directory contents:"
          ls -la .next/
          if [ ! -f ".next/BUILD_ID" ]; then
            echo "BUILD_ID file not found!"
            exit 1
          fi

      # 确保 .next 目录被包含在 zip 中，并排除不必要的文件
      - name: Zip artifact for deployment
        run: |
          echo "Creating deployment package..."
          zip -r release.zip . -x "*.git*" "*.github*" "node_modules/.cache/*" "*.map" "*.log"
          echo "Verifying zip contents:"
          unzip -l release.zip | grep .next/
          du -sh release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 30  # 添加超时设置

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_029B35931F9A430DAF29AAAD877FEE41 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ADCCA55F290C4CCDA738BB525A0109E4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F93D0492C2B9485BA89305381EF23CF7 }}

      # 创建自定义部署脚本
      - name: Create deployment scripts
        run: |
          echo "创建自定义部署脚本..."
          echo '[config]' > .deployment
          echo 'command = bash deploy.sh' >> .deployment
          
          cat > deploy.sh << 'EOL'
          #!/bin/bash
          
          # 优化内存使用
          export NODE_OPTIONS="--max-old-space-size=4096"
          
          # 设置启动命令
          echo "node server.js" > startup.txt
          
          echo "部署完成!"
          exit 0
          EOL
          
          chmod +x deploy.sh
          
          # 创建web.config
          cat > web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <webSocket enabled="false" />
              <handlers>
                <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
              </handlers>
              <rewrite>
                <rules>
                  <rule name="StaticContent">
                    <action type="Rewrite" url="public{REQUEST_URI}" />
                  </rule>
                  <rule name="DynamicContent">
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True" />
                    </conditions>
                    <action type="Rewrite" url="server.js" />
                  </rule>
                </rules>
              </rewrite>
              <iisnode 
                nodeProcessCommandLine="node.exe --max-old-space-size=4096"
                watchedFiles="*.js;node_modules\*;routes\*.js;views\*.jade"
                loggingEnabled="true"
                logDirectory="iisnode"
                maxLogFileSizeInKB="1024"
                maxTotalLogFileSizeInKB="20480"
                maxLogFiles="20"
              />
              <security>
                <requestFiltering>
                  <hiddenSegments>
                    <remove segment="bin" />
                  </hiddenSegments>
                </requestFiltering>
              </security>
            </system.webServer>
          </configuration>
          EOL

      # 在部署前安装生产依赖
      - name: Install production dependencies
        run: |
          npm ci --only=production --no-optional
          ls -la .next/

      # 设置应用设置
      - name: Set Web App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'Farmgazer-2-new'
          slot-name: 'Production'
          app-settings-json: |
            [
              {
                "name": "NODE_ENV",
                "value": "production",
                "slotSetting": false
              },
              {
                "name": "PORT",
                "value": "3000",
                "slotSetting": false
              },
              {
                "name": "WEBSITES_PORT",
                "value": "3000",
                "slotSetting": false
              },
              {
                "name": "NODE_OPTIONS",
                "value": "--max-old-space-size=4096",
                "slotSetting": false
              },
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "~20",
                "slotSetting": false
              },
              {
                "name": "SCM_COMMAND_IDLE_TIMEOUT",
                "value": "1800",
                "slotSetting": false
              },
              {
                "name": "AZURE_SQL_SERVER",
                "value": "${{ secrets.AZURE_SQL_SERVER }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_SQL_DATABASE",
                "value": "${{ secrets.AZURE_SQL_DATABASE }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_SQL_USER",
                "value": "${{ secrets.AZURE_SQL_USER }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_SQL_PASSWORD",
                "value": "${{ secrets.AZURE_SQL_PASSWORD }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_STORAGE_CONNECTION_STRING",
                "value": "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}",
                "slotSetting": false
              },
              {
                "name": "AZURE_STORAGE_CONTAINER_NAME",
                "value": "${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}",
                "slotSetting": false
              }
            ]

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Farmgazer-2-new'
          slot-name: 'Production'
          package: .
          clean: true
          startup-command: 'node server.js'